#pragma once

const char* html_page =
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html\r\n\r\n"
"<!DOCTYPE html>\n"
"<html lang=\"pt-BR\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>Status do Botão</title>\n"
"  <style>\n"
"    body {\n"
"      background-color: #1a1a1a;\n"
"      color: #ffffff;\n"
"      font-family: Arial, sans-serif;\n"
"      text-align: center;\n"
"      padding-top: 50px;\n"
"    }\n"
"    .card {\n"
"      background: #2e2e2e;\n"
"      border-radius: 10px;\n"
"      padding: 30px;\n"
"      display: inline-block;\n"
"      box-shadow: 0 0 10px rgba(0,0,0,0.5);\n"
"    }\n"
"    #status {\n"
"      font-size: 2rem;\n"
"      margin-top: 20px;\n"
"      padding: 10px;\n"
"      border-radius: 8px;\n"
"      display: inline-block;\n"
"      background-color: gray;\n"
"    }\n"
"    .pressed { background-color: #28a745; color: white; }\n"
"    .released { background-color: #dc3545; color: white; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"card\">\n"
"    <h1>Monitoramento do Botão (GPIO 5)</h1>\n"
"    <div id=\"status\">Carregando...</div>\n"
"  </div>\n"
"  <script>\n"
"    function atualizarStatus() {\n"
"      fetch('/status')\n"
"        .then(resp => resp.text())\n"
"        .then(texto => {\n"
"          const status = document.getElementById('status');\n"
"          status.textContent = texto;\n"
"          status.className = (texto.includes('PRE')) ? 'pressed' : 'released';\n"
"        });\n"
"    }\n"
"    setInterval(atualizarStatus, 1000);\n"
"    atualizarStatus();\n"
"  </script>\n"
"</body>\n"
"</html>\n";


/*
const char *html_page =
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html\r\n\r\n"
"<!DOCTYPE html>\n"
"<html>\n"
"<head><title>GPIO 5 Monitor</title></head>\n"
"<body>\n"
"<h1>Status do Botao no GPIO 5</h1>\n"
"<p id='status'>Carregando...</p>\n"
"<script>\n"
"setInterval(() => {\n"
" fetch('/status')\n"
"  .then(res => res.text())\n"
"  .then(txt => document.getElementById('status').innerText = txt);\n"
"}, 1000);\n"
"</script>\n"
"</body>\n"
"</html>\n";
*/